name: flutter_laboratory
description: A flutter application for having a better devtools experience.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  go_router: ^9.0.3
  flutter_bloc: ^8.1.3
  vm_service: ^11.7.2
  dio: ^5.2.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: UbuntuMono
      fonts:
        - asset: fonts/UbuntuMono/UbuntuMono-Regular.ttf
        - asset: fonts/UbuntuMono/UbuntuMono-Bold.ttf
          weight: 700
        - asset: fonts/UbuntuMono/UbuntuMono-Italic.ttf
          style: italic
        - asset: fonts/UbuntuMono/UbuntuMono-BoldItalic.ttf
          weight: 700
          style: italic
